//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_BITMAP1                     102
#define IDB_CHARS                       102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDB_P_COLLISION_BOX             106
#define IDB_RESPAWN_COURIER_LEFT        107
#define IDB_RESPAWN_COURIER_R           108
#define IDB_RESPAWN_COURIER_RIGHT       108
#define IDB_FX_EXPLO_LEFT0              113
#define IDB_FX_EXPLO_LEFT1              114
#define IDB_FX_EXPLO_LEFT2              115
#define IDB_FX_EXPLO_LEFT3              116
#define IDB_FX_EXPLO_RIGHT0             117
#define IDB_FX_EXPLO_RIGHT1             118
#define IDB_FX_EXPLO_RIGHT2             119
#define IDB_FX_EXPLO_RIGHT3             120
#define IDB_FX_EXPLO_DOWN0              125
#define IDB_FX_EXPLO_DOWN1              126
#define IDB_FX_EXPLO_DOWN2              127
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_FX_EXPLO_DOWN3              129
#define IDB_FX_EXPLO_UP0                130
#define IDB_FX_EXPLO_UP1                131
#define IDB_FX_EXPLO_UP2                132
#define IDB_FX_EXPLO_UP3                133
#define IDB_TAKEN_DMG_GREEN             134
#define IDB_TAKEN_DMG_RED               135
#define IDB_BITMAP5                     136
#define IDB_TAKEN_DMG_YELLOW            136
#define IDC_GAMECURSOR                  153
#define IDB_LOADING                     156
#define IDB_CONTINUE                    158
#define IDB_GROUND1                     162
#define IDB_GROUND2                     163
#define IDB_BACKGROUND1                 168
#define IDB_BACKGROUND2                 169
#define IDB_BITMAP9                     391
#define IDR_UI_TITLE                    395
#define IDB_WEAPON_FALLING              500
#define IDB_BITMAP8                     520
#define IDB_BITMAP4                     532
#define IDB_FX_SKILL0_L0                549
#define IDB_FX_SKILL0_L1                550
#define IDB_FX_SKILL0_L2                551
#define IDB_FX_SKILL0_R0                552
#define IDB_FX_SKILL0_R1                553
#define IDB_FX_SKILL0_R2                554
#define IDB_P_LOUIS_R0                  555
#define IDB_P_LOUIS_L0                  556
#define IDB_P_LOUIS_R1                  557
#define IDB_P_LOUIS_L1                  558
#define IDB_P_LOUIS_R2                  559
#define IDB_P_LOUIS_L2                  560
#define IDB_P_LOUIS_EX_R0               561
#define IDB_P_LOUIS_EX_L0               562
#define IDB_P_LOUIS_EX_R1               563
#define IDB_P_LOUIS_EX_L1               564
#define IDB_P_LOUIS_EX_R2               565
#define IDB_P_LOUIS_EX_L2               566
#define IDB_P_LOUIS_EX_R3               567
#define IDB_P_LOUIS_EX_L3               568
#define IDB_P_JULIAN_R0                 569
#define IDB_P_JULIAN_L0                 570
#define IDB_P_JULIAN_R1                 571
#define IDB_P_JULIAN_L1                 572
#define IDB_P_JULIAN_R2                 573
#define IDB_P_JULIAN_L2                 574
#define IDB_WEAPON_ROT_L                600
#define IDB_WEAPON_ROT_L_45             601
#define IDB_WEAPON_ROT_L_90             602
#define IDB_WEAPON_ROT_L_135            603
#define IDB_WEAPON_ROT_L_180            604
#define IDB_WEAPON_ROT_L_225            605
#define IDB_WEAPON_ROT_L_270            606
#define IDB_WEAPON_ROT_L_315            607
#define IDB_WEAPON_ROT_R                608
#define IDB_WEAPON_ROT_R_45             609
#define IDB_WEAPON_ROT_R_90             610
#define IDB_WEAPON_ROT_R_135            611
#define IDB_WEAPON_ROT_R_180            612
#define IDB_WEAPON_ROT_R_225            613
#define IDB_WEAPON_ROT_R_270            614
#define IDB_WEAPON_ROT_R_315            615
#define IDS_PUNCH                       750
#define IDS_BATTLE_MUSIC                751
#define IDS_DRAW_WEAPON                 752
#define IDS_SWOOSH                      753
#define IDS_SWING_ATTACK                754
#define IDS_MENU_MUSIC                  755
#define IDB_NUM0                        1000
#define IDB_NUM1                        1001
#define IDB_NUM2                        1002
#define IDB_NUM3                        1003
#define IDB_NUM4                        1004
#define IDB_NUM5                        1005
#define IDB_NUM6                        1006
#define IDB_NUM7                        1007
#define IDB_NUM8                        1008
#define IDB_NUM9                        1009
#define IDB_NUM_MINUS                   1010
#define IDC_README                      1012
#define IDB_UI_TITLE                    2000
#define IDB_UI_BACKGROUND               2001
#define IDB_UI_INFO1                    2002
#define IDB_UI_INFO2                    2003
#define IDB_UI_INFO3                    2004
#define IDB_UI_INFO4                    2005
#define IDB_UI_BUTTON0_OUT              2006
#define IDB_UI_BUTTON0_HOV              2007
#define IDB_UI_BUTTON0_CLK              2008
#define IDB_UI_BUTTON1_OUT              2009
#define IDB_UI_BUTTON1_HOV              2010
#define IDB_UI_BUTTON1_CLK              2011
#define IDB_UI_BUTTON2_OUT              2012
#define IDB_UI_BUTTON2_HOV              2013
#define IDB_UI_BUTTON2_CLK              2014
#define IDB_UI_BUTTON3_OUT              2015
#define IDB_UI_BUTTON3_HOV              2016
#define IDB_UI_BUTTON3_CLK              2017
#define IDB_UI_BUTTON4_OUT              2018
#define IDB_UI_BUTTON4_HOV              2019
#define IDB_UI_BUTTON4_CLK              2020
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
